### ISSUE TITLE
Geofence Accuracy: Adjust precision?

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#166]
When navigating to the parking zone, distance in time is not accurate getting closer.  It shows 0 time when you're still a distance from the final destination.  This is important for confidence and timing since we're waiting.

**Comment by vfxdrummer** [comment]
This is mostly an issue because the time is in minutes, so anything less than a minute it calls zero.
I will switch to seconds when less than a minute. Also, it is computing the estimatedTime using the vendor location, and not accounting for the geofence, which is closer. This is mostly an issue when you get close to arrival. We can multiply the estimated time by the proper ratio to account for the geofence as the destination.
