### ISSUE TITLE
Analytics:  Decide on Analytics package

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#78]
@yuriisekretar @danipralea  @vfxdrummer , preferences on an analytics package?  Simple, straightforward to implement is good.

Thinking from a marketing perspective, we want to track campaign performance by user engagement.

**Comment by vfxdrummer** [comment]
Mixpanel is always good. 
https://mixpanel.com

Firebase also has built-in analytics.
https://firebase.google.com/docs/analytics/

From what I have seen, the Firebase dashboards seem pretty solid. You may want to check it out.

We should build an analytics manager to register our events, so that we are able to easily send them to any analytics Service from one central spot.

**Comment by kevinp** [comment]
@vfxdrummer , that i perfect.  Let's go with the built-in Google Analytics for Firebase.

**Comment by vfxdrummer** [comment]
Ok, Sounds Good. Gonna set up an EventManager to report it.
